version: '3'
services:
  web:
    build: ./pro
    restart: on-failure:20
    command:  bash -c "
             python manage.py shell < test_connect_to_db.py
             && python manage.py makemigrations
             && python manage.py migrate
             && python manage.py runserver 0.0.0.0:8000
           "
    ports:
     - 8000:8000
    volumes:
     - ./pro:/data
    depends_on:
     - db
  db:
    image: mysql:5.7
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: new_base
#    ports:
#      - '3307:3306'
#    expose:
#      - '3307'
    command: --init-file /data/application/init.sql
    volumes:
      - ./db:/var/lib/mysql
      - ./mycustom.cnf:/etc/mysql/conf.d/custom.cnf
      - ./init.sql:/data/application/init.sql
